### ISSUE TITLE
How to Monkey Patch BASE_URL?

### ISSUE THREAD

**Issue by vurezo** [sergey-scat/unicaps#10]
Hey, instead of BASE_URL = "https://2captcha.com" it needs to be BASE_URL = "http://mydomain:1234"
how can I monkey patch this so it looks clean?
I'm using it with XEvil

Also, how do I change these params?

    def _post_init(self):
        """ Init settings """

        for captcha_type in self.settings:
            self.settings[captcha_type].polling_interval = 2

I don't want it to poll every 2 seconds I want it to poll every 5 seconds

**Comment by sergey-scat** [comment]
XEvil is not supported.
