### ISSUE TITLE
Please add Custom2Captcha XEvil

### ISSUE THREAD

**Issue by vurezo** [sergey-scat/unicaps#11]
Please add me on Discord
Dmitry#3429

For more details & test environment

Just changing the 2Captcha URL doesn't work, it gives this error:
10/13/2022 12:09:33 PM: POST /in.php
10/13/2022 12:09:33 PM: Wrong API Key = [] rejected!
10/13/2022 12:09:33 PM: .\Lua\API\emulation.lua:32: attempt to compare number with nil

**Comment by sergey-scat** [comment]
I don't have XEvil installed.
I can add it if you install XEvil on a server (with dedicated IP) and provide me with the URL.

**Comment by vurezo** [comment]
BASE URL: http://95.216.229.102:666
API: 2Captcha like

key:
c32c6a43debd428defa0dccee6ed22b7
123test

Might work as just 2Captcha but minor tweak for how the key is being passed

**Comment by sergey-scat** [comment]
Thx.
It seems that the 2captcha interface is not fully implemented in XEvil.
Can you switch to anti-captcha (in XEvil it's called "Antigate v2" or something like that)?

**Comment by vurezo** [comment]
Done, when you implement it please make sure you can specify the base url =) thank you so much

**Comment by sergey-scat** [comment]
XEvil works better through the Anti-Captcha interface (but, for me, only reCAPTCHA v2 it solves correctly... I have no idea why).
The following code can be used as a workaround:
```python
from unicaps import CaptchaSolver, CaptchaSolvingService

# init Anti-captcha solver
solver = CaptchaSolver(CaptchaSolvingService.ANTI_CAPTCHA, 'c32c6a43debd428defa0dccee6ed22b7')

# change BASE_URL
solver._service.BASE_URL = 'http://95.216.229.102:666'

# get balance
print(f'Balance: {solver.get_balance()}')

# solve reCAPTCHA v2
solved = solver.solve_recaptcha_v2(
    site_key='6LfW6wATAAAAAHLqO2pb8bDBahxlMxNdo9g947u9',
    page_url='https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox.php'
)
print(solved.solution.token)
```

Please try it and let me know if it works for you.

**Comment by vurezo** [comment]
fuck yeah buddy will do

**Comment by vurezo** [comment]
works :)

**Comment by sergey-scat** [comment]
Ok, closing then
