### ISSUE TITLE
can you look into if nocaptchaai.com api can be added?

### ISSUE THREAD

**Issue by 404b** [sergey-scat/unicaps#6]
i've tried the services solves pretty fast and has good accuracy around 98 out of 100 challenges. Read on their discord they might have a refer system too. Anyway good work on this repo tho.

**Comment by sergey-scat** [comment]
Thanks for the suggestion.
This package supports hCaptcha and reCAPTCHA via token only, "Grid" type captcha is not supported and is not planned to add yet.
